### PR TITLE
🎨 Make var UniFlowLogger.logger public

### PR DESCRIPTION
**Pull request by erikhuizinga**
There are multiple reasons for this:

 - `init()` sets the `logger` property in any case, making it practically a `var` with a private getter.
 - In tests you may want to replace the current logger with a custom one, but after the test you want to reset this to the previous one. For this you need to know what the default / previous logger was, so you can restore it. So the getter now also is public.

So I've simply made the `var` public and refactored all uses of `init()` with direct property access.

### CODE REVIEW

**Comment by erikhuizinga** [comment]
Maybe a simpler alternative would be to stick with the `init()` method and the `private var logger`, but also provide a `fun default(): Unit` (or `reset()`) that resets the `UniFlowLogger` to the default?

**Comment by MarcinChrapowicz** [comment]
From what I can see you are able to change logger, without adding any extra methods. We can do that using this method `UniFlowLogger.init(DebugMessageLogger())`, it should work from what I know 🤞. 
This function gives you a possibility to change logger to a custom one 
```
fun init(logger: Logger) {
        this.logger = logger
    }

**Comment by erikhuizinga** [comment]
True, but how do I change it back to the default logger? As a user of uniflow I don't know what the default logger is.

Yes, I can look into the source and see that _currently_ `SimpleMessageLogger()` is used. So what I could do in my test is

1. `init(MyTestLogger())`
1. Run tests
1. `init(SimpleMessageLogger())`

But there is a problem: nothing protects me from future changes to uniflow, and if the default logger is no longer `SimpleMessageLogger()`, then I'd change back to the non-default logger.

This is why, as a user, I want uniflow to either:

- Tell me what the default logger is, e.g. by making `var logger` public.
- Provide a `default` or `reset` function to reset to the default, which is uniflow's internal choice.

**Comment by MarcinChrapowicz** [comment]
Thanks for time and explanation 👍, I think ideal will be have a function `default` to reset to the default

**Comment by erikhuizinga** [comment]
Superseded by #17.

**Pull request closed without merging**
