### PR TITLE
Remove error print to the standard error stream

### PR DESCRIPTION
**Pull request by erikhuizinga**

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Hi @erikhuizinga 

I had to add it to display stacktrace, but yes I can remove it by default.

**Comment by arnaudgiuliani** [comment]
@erikhuizinga could we replace error stacktrace printing with:

```kotlin
UniFlowLogger.logError("Uncaught error: $error - ${error.stackTrace}", error)
```

**Comment by erikhuizinga** [comment]
Doesn't simply logging `"Uncaught error: $error"` already print the stack trace?

**Comment by arnaudgiuliani** [comment]
nope, we don't have any info regarding the stack trace :/ The cause message is just flatten.

**Pull request merged**
